news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("users/", include("users.urls")),
    path("", include("newsapp.urls")),
    path("publishers/", include("publishers.urls")),
    

    # URL pattern for displaying password_reset view
    path('forgot-password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'
    ), name='password_reset'),

    path('forgot-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ),  name='password_reset_complete'),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_project/newsapp/urls.py
from django.urls import path
from .views import (
    create_article,
    dashboard,
    article_list,
    editor_dashboard,
    journalist_dashboard,
    approve_article,
    article_detail,
    article_update,
    article_delete,
    reader_dashboard,
    confirm_subscription,
    subscribe,
    unsub_to_journalist,
    unsub_to_publisher,
    newsletter_detail,
    newsletter_create,
    newsletter_update,
    newsletter_delete,
    subscribed_articles,
)

app_name = 'newsapp'

urlpatterns = [
    path('create/', create_article, name='create_article'),

    path('', dashboard, name='dashboard'),

    path('editor_dashboard/', editor_dashboard, name='editor_dashboard'),

    path('journalist/dashboard', journalist_dashboard, name="journalist_dashboard"),

    path('reader/dashboard/', reader_dashboard, name="reader_dashboard"),

    path('articles/article_list', article_list, name='article_list'),

    path('article/detail/<int:pk>/', article_detail, name='article_detail'),

    path('articles/update/<int:pk>/', article_update, name="article_update"),

    path('articles/delete/<int:pk>', article_delete, name="article_delete"),

    path("subscribe/confirm/<int:pk>/", confirm_subscription, name="confirm_subscription"),

    path("subscribe/<int:pk>/", subscribe, name="subscribe"),

    # path("subscribe/", subscribe, name="subscribe"),

    path('unsub/publisher/<int:pk>/', unsub_to_publisher, name="unsub_to_publisher"),

    path('unsub/journalist/<int:pk>/', unsub_to_journalist, name='unsub_to_journalist'),

    path('newsletter/detail', newsletter_detail, name='newsletter_detail'),

    path('newsletter/create', newsletter_create, name='newsletter_create'),

    path('newsletter/update', newsletter_update, name='newsletter_update'),

    path('newsletter/delete', newsletter_delete, name='newsletter_delete'),

    path('articles/approve/<int:pk>/', approve_article, name="approve_article"),

    path('api/subscribed-articles/<int:pk>/', subscribed_articles, name='subscribed-articles'),
]

news_project/publishers/urls.py
from django.urls import path
from .views import (
    send_invitation,
    create_publication,
    send_invite,
    request_join,
    view_invitations,
    accept_invite
)

app_name = 'publishers'

urlpatterns = [
    path('invite/', send_invitation, name='send_invitation'),

    path('publishers/create_publication/', create_publication, name='create_publication'),

    path('publishers/send_invite/<int:pk>/', send_invite, name="send_invite"),

    path('send_invitation/<int:pk>/', send_invitation, name="send_invitation"),

    # publishers/urls.py
    path("invitations/", view_invitations, name="view_invitations"),

    # publishers/urls.py
    path("request-join/", request_join, name="request_join"),

    path("accept-invite/<str:token>/", accept_invite, name="accept_invite"),
]

news_project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    signup,
    login,
    logout_user,
    profile,
    reader_homepage,
    journalist_homepage,
    editor_homepage,
    sub_to_publisher,
    sub_to_journalist,
    unsub_to_journalist,
    unsub_to_publisher
)

app_name = 'users'

urlpatterns = [
    # URL pattern for displaying signup view
    path("", signup, name="signup"),

    # URL pattern for displaying login_view
    path("login", login, name="login"),

    # URL pattern for loggin out user
    path("logout", logout_user, name="logout_user"),


    # URL pattern for displaying profile
    path("profile/", profile, name="profile"),

    # URL pattern for displaying password_reset view
    path('forgot-password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'
    ), name='password_reset'),

    path('forgot-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ),  name='password_reset_complete'),

    path('reader-homepage/', reader_homepage, name='reader_homepage'),
    path('journalist-homepage/', journalist_homepage, name='journalist_homepage'),
    path('editor-homepage/', editor_homepage, name='editor_homepage'),

    # subscription paths
    path('subscribe/journalist/<int:pk>/', sub_to_journalist, name='sub_to_journalist'),
    path('subscribe/publisher/<int:pk>/', sub_to_publisher, name='sub_to_publisher'),

    path('unsubscribe/journalist/<int:pk>/', unsub_to_journalist, name='unsub_to_journalist'),
    path('unsubscribe/publisher/<int:pk>/', unsub_to_publisher, name='unsub_to_publisher'),
]

news_project/newsapp/views.py
import tweepy

from django.shortcuts import render, get_object_or_404, redirect
from .forms import ArticleForm, NewsletterForm
from users.models import CustomUser
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Article, Newsletter
from publishers.models import Publisher
from publishers.views import join_requests
from django.http import HttpResponseForbidden
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import ArticleSerializer


def announce_article_on_x(article_id):
    '''
    View to announce an article on X (formerly Twitter).

    :param article_id: ID of the article to be announced.
    :return: None. Posts a text-only announcement to X if the article exists.
    '''
    # Validating the article object.
    try:
        article = Article.objects.select_related().get(id=article_id)
    except Article.DoesNotExist:
        return
    client = tweepy.Client(
        consumer_key=settings.TWITTER_API_KEY,
        consumer_secret=settings.TWITTER_API_SECRET,
        access_token=settings.TWITTER_ACCESS_TOKEN,
        access_token_secret=settings.TWITTER_ACCESS_TOKEN_SECRET,
    )
    # Image settings.
    # auth = tweepy.OAuth1UserHandler(consumer_key=settings.TWITTER_API_KEY, consumer_secret=settings.TWITTER_API_SECRET, access_token=settings.TWITTER_ACCESS_TOKEN, access_token_secret=settings.TWITTER_ACCESS_TOKEN_SECRET)
    # v1_api = tweepy.API(auth)
    # media = v1_api.media_upload(store.cover_page.path)

    # X post (tweet).
    client.create_tweet(text=f"New Article Added: {article.title}")


@login_required
def create_article(request):
    '''
    View to create a new article.
    :param request: HTTP request object.
    :return: Rendered template for creating a new article.
    '''
    if request.method == "POST":
        form = ArticleForm(request.POST, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)

            # Always set the author
            article.author = request.user

            # Attach publication if the journalist belongs to one
            publishers = request.user.joined_publishers.all()
            if publishers.exists():
                article.publisher = publishers.first()
            else:
                # Independent journalist
                article.publisher = None
                # article.independent_author.set(request.user)

            # Force safe defaults
            # article.status = "pending"        # Never published automatically
            # article.is_approved = False     # Never approved automatically

            article.save()
            article.independent_author.add(request.user)
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(user=request.user)

    return render(request, "articles/article_form.html", {"form": form})


@login_required
def article_list(request):
    '''
    This view will display a list of articles/newsletters

        :param request: HTTP object
        :return: Rendered template with a list of articles/newsletters
    '''
    articles = Article.objects.filter(is_approved=True)
    newsletters = Newsletter.objects.filter(is_approved=True)

    context = {
        "articles": articles,
        "newsletters": newsletters,
        "page_title": "All Articles"
    }

    return render(request, "articles/article_list.html", context)


@login_required
def article_detail(request, pk):
    '''
    View to display details of a specific article.
    :param request: HTTP request object.
    :param pk: Primary key of the article.
    :return: Rendered template with details of the specified article.
    '''
    article = get_object_or_404(Article, pk=pk)
    context = {
        "article": article
    }
    return render(request, "articles/article_detail.html", context)


@login_required
def article_update(request, pk):
    '''
    View to update an existing article.
    :param request: HTTP request object.
    :param pk: Primary key of the article to be updated.
    :return: Rendered template for updating the specified article.
    '''

    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)
            article.save()
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(instance=article, user=request.user)
    return render(request, "articles/article_form.html", {"form": form})


@login_required
def article_delete(request, pk):
    '''
    View to delete an existing article.
    :param request: HTTP request object.
    :param pk: Primary key of the article to be deleted.
    :return: Redirect to the article list after deletion.
    '''

    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect("newsapp:article_list")


@login_required
def newsletter_create(request):
    '''
    View to create a new newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to the article list after creation.
    '''
    if request.method == "POST":
        form = NewsletterForm(request.POST, user=request.user)
        if form.is_valid():
            newsletter = form.save(commit=False)

            # Always set the author
            newsletter.author = request.user

            # Attach publication if the journalist belongs to one
            publishers = request.user.joined_publishers.all()
            if publishers.exists():
                newsletter.publisher = publishers.first()
            else:
                # Independent journalist
                newsletter.publisher = None
                # article.independent_author.set(request.user)

            newsletter.save()
            newsletter.independent_author.add(request.user)
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(user=request.user)

    return render(request, "articles/article_form.html", {"form": form})


def newsletter_list(request):
    '''
    This view will display a list of articles/newsletters

        :param request: HTTP object
        :return: Rendered template with a list of articles/newsletters
    '''
    if request.user.role == 'reader':
        newsletters = Newsletter.objects.filter(is_approved=True)
    else:
        newsletters = Newsletter.objects.all()

        context = {
            "newsletters": newsletters,
            "page_title": "All newsletters"
        }

        return render(request, "newsletters/newsletter_list.html", context)


@login_required
@user_passes_test(lambda u: u.role == 'editor')
def newsletter_update(request, pk):
    '''
    View to update an existing newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter to be updated.
    :return: Rendered template for updating the specified newsletter.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        form = NewsletterForm(request.POST, instance=newsletter)
        if form.is_valid():
            newsletter = form.save(commit=False)
            newsletter.journalist = request.user
            newsletter.publisher = request.publisher
            form.save()
        return redirect("newsletters: newsletter_list")
    else:
        form = NewsletterForm()
    return render(request, "newsletters/newsletter_form.html", {"form": form})


@login_required
@user_passes_test(lambda u: u.role == 'editor')
def newsletter_delete(request, pk):
    '''
    View to delete an existing newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter to be deleted.
    :return: Redirect to the newslleter list after deletion.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    newsletter.delete()
    return redirect("newsletters: newsletter_list")


def newsletter_detail(request, pk):
    '''
    View to display details of a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Rendered template with details of the specified newsletter.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    context = {
        "newsletter": newsletter
    }
    return render(request, "newsletters/newsletter_detail.html", context)


def approve_newsletter(request, pk):
    '''
    View to display approve a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to newsletter_list.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.user.role == 'editor':
        newsletter.is_approved = True
        newsletter.save()
    return redirect('newsletters:newsletter_list')


def reject_newsletter(request, pk):
    '''
    View to display reject a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to newsletter_list.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.user.role == 'editor':
        newsletter.is_approved = False
        newsletter.save()
    return redirect('newsletters:newsletter_list')


def approve_article(request, pk):
    '''
    View to display approve a specific article.
    :param request: HTTP request object.
    :param pk: Primary key of the article.
    :return: Redirect to article_list.
    '''
    article = get_object_or_404(Article, pk=pk)
    if request.user.role == 'editor':
        article.is_approved = True
        # announce_article_on_x(article_id=article.id)
        article.save()
    return redirect('newsapp:article_list')

news_project/newsapp/templates/newsapp/admin_dashboard.html
{% extends 'base.html' %}
{% block content %}
    <h1>Admin Dashboard</h1>
    <p>Welcome, {{ user.username }}!</p>
    <p>Email: {{ user.email }}</p>
    <p>Role: {{ user.role|title }}</p>

    <h2>All Users</h2>
    <ul>
        {% for u in all_users %}
            <li>{{ u.username }} - {{ u.email }} - {{ u.role|title }}</li>
        {% empty %}
            <li>No users found.</li>
        {% endfor %}
    </ul>

    <h2>All Publishers</h2>
    <ul>
        {% for publisher in all_publishers %}
            <li>{{ publisher.name }} - <a href="{{ publisher.website }}">{{ publisher.website }}</a></li>
        {% empty %}
            <li>No publishers found.</li>
        {% endfor %}
        <li>Create new publisher - <a href="{% url 'publishers:create_publisher' %}">Create Publisher</a></li>
    </ul>
{% endblock %}

news_project/newsapp/templates/newsapp/confirm_subscription.html
{% extends "base.html" %}

{% block content %}

<style>
.confirm-box {
    max-width: 480px;
    margin: 80px auto;
    padding: 30px;
    border: 1px solid #eaeaea;
    border-radius: 8px;
    text-align: center;
}

.confirm-box h2 {
    margin-bottom: 12px;
}

.confirm-box p {
    color: #555;
    margin-bottom: 24px;
}

.actions {
    display: flex;
    justify-content: center;
    gap: 12px;
}

.btn {
    padding: 8px 16px;
    border-radius: 6px;
    border: none;
    cursor: pointer;
    font-size: 0.9rem;
}

.btn-confirm {
    background-color: #2563eb;
    color: #fff;
}

.btn-confirm:hover {
    background-color: #1d4ed8;
}

.btn-cancel {
    background-color: #e5e7eb;
    color: #111;
}
</style>

<div class="confirm-box">
    <h2>Confirm subscription</h2>

    {% if target_type == "journalist" %}
        <p>Are you sure you want to subscribe to journalist <strong>{{ target.get_full_name|default:target.username }}</strong>?</p>
    {% else %}
        <p>Are you sure you want to subscribe to publisher <strong>{{ target.name }}</strong>?</p>
    {% endif %}

    <form method="post" action="{% url 'newsapp:subscribe' article.pk %}">
        {% csrf_token %}
        <button type="submit">Yes, subscribe</button>
        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>
{% endblock %}

news_project/newsapp/templates/newsapp/create_project.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create a New Project</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_project_type">Select Project Type:</label>
        <select name="project_type" id="id_project_type">
            <option value="article">Article</option>
            <option value="newsletter">Newsletter</option>
        </select>
        <button type="submit">Create</button>
    </form>
{% endblock %}

news_project/newsapp/templates/newsapp/editor_dashboard.html
{% extends 'base.html' %}


{% comment %} {% block title %}Editor Dashboard - NewsApp 2026{% endblock %}

{% block content %}
<div class="flex flex-col items-center justify-center min-h-[70vh] px-4">
    <div class="text-center mb-12">
        <h2 class="text-4xl font-extrabold text-slate-800 tracking-tight">Editor Command Center</h2>
        <p class="text-gray-500 mt-2">Select an action to manage your news desk.</p>
    </div> {% endcomment %}

    <!-- Triple Action Button Grid -->
    {% comment %} <div class="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-5xl">
        
        <!-- Workspace Button -->
        <a href="{% url 'newsapp:workspace' %}" class="group flex flex-col items-center p-8 bg-white border border-gray-200 rounded-2xl shadow-sm hover:shadow-xl hover:border-blue-500 transition-all transform hover:-translate-y-2 text-center">
            <div class="w-16 h-16 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center mb-4 group-hover:bg-blue-600 group-hover:text-white transition">
                <i class="fa-solid fa-briefcase text-2xl"></i>
            </div>
            <span class="text-xl font-bold text-slate-800">Open Workspace</span>
            <p class="text-sm text-gray-400 mt-2">Manage ongoing drafts and active edits.</p>
        </a>

        <!-- Create Publication Button -->
        <a href="{% url 'publishers:create_publication' %}" class="group flex flex-col items-center p-8 bg-white border border-gray-200 rounded-2xl shadow-sm hover:shadow-xl hover:border-emerald-500 transition-all transform hover:-translate-y-2 text-center">
            <div class="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center mb-4 group-hover:bg-emerald-600 group-hover:text-white transition">
                <i class="fa-solid fa-plus text-2xl"></i>
            </div>
            <span class="text-xl font-bold text-slate-800">New Publication</span>
            <p class="text-sm text-gray-400 mt-2">Start a new story or daily edition.</p>
        </a>

        <!-- Add Members Button -->
        <a href="{% url 'publishers:send_invitation' %}" class="group flex flex-col items-center p-8 bg-white border border-gray-200 rounded-2xl shadow-sm hover:shadow-xl hover:border-purple-500 transition-all transform hover:-translate-y-2 text-center">
            <div class="w-16 h-16 bg-purple-50 text-purple-600 rounded-full flex items-center justify-center mb-4 group-hover:bg-purple-600 group-hover:text-white transition">
                <i class="fa-solid fa-user-plus text-2xl"></i>
            </div>
            <span class="text-xl font-bold text-slate-800">Manage Team</span>
            <p class="text-sm text-gray-400 mt-2">Invite and add members to your desk.</p>
        </a> {% endcomment %}
        {% comment %} <nav>
            <a href="{% url 'newsapp:workspace' %}">Open workspace</a>
        </nav>
        <nav>
            <a href="{% url 'publishers:create_publication' %}" class="btn-norm"> Create publication</a>
        </nav>

        <nav>
            <a href="{% url 'publishers:send_invitation' %}" class="btn-norm"> + manage team</a>
        </nav>
    </div>
</div>

{% endblock %} {% endcomment %}

{% block content %}
<div class="dashboard-header">
    <h1>{{ publisher.name }} Control Room</h1>
    <p>Managing Editor: {{ request.user.username }}</p>
</div>

<div class="grid">
    <section class="article-card">
        <h3>Pending Articles ({{ pending_articles.count }})</h3>
        {% for article in pending_articles %}
            <div style="border-bottom: 1px solid #eee; padding: 10px 0;">
                <strong>{{ article.title }}</strong> by {{ article.author.username }}
                <br>
                <small>Submitted: {{ article.created_at|date }}</small>
                <div style="margin-top: 10px;">
                    <a href="{% url 'article_approve' article.id %}" class="btn-publish" style="font-size: 0.8rem;">Review & Publish</a>
                </div>
            </div>
        {% empty %}
            <p>No articles waiting for review.</p>
        {% endfor %}
    </section>

    <section class="article-card">
        <h3>Staff Directory</h3>
        <ul>
            {% for member in staff %}
                <li>{{ member.username }} - <mark>{{ member.role|title }}</mark></li>
            {% endfor %}
        </ul>
        <a href="{% url 'send_invite' %}" class="secondary">Invite Journalist</a>
    </section>
</div>
{% endblock %}

news_project/newsapp/templates/newsapp/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>index</title>
</head>
<body>
    <h1>Latest News</h1>
    <h2>Articles</h2>
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a></li>
        {% empty %}
            <li>No articles available.</li>
        {% endfor %}
    </ul>

    <h2>Newsletters</h2>
    <ul>
        {% for newsletter in newsletters %}
            <li><a href="{% url 'newsletters:newsletter_detail' newsletter.pk %}">{{ newsletter.title }}</a></li>
        {% empty %}
            <li>No newsletters available.</li>
        {% endfor %}
    </ul>
</body>
</html>

news_project/newsapp/templates/newsapp/my_projects.html
{% extends 'base.html' %}

{% block content %}
    <h1>My Projects</h1>

    <ul>
        {% with all_projects=my_projects.articles|add:my_projects.newsletters %}
            {% for project in all_projects %}
                <li>
                    {% if project.type == 'article' %}
                        <strong>Article:</strong> {{ project.title }} - <a href="{{ project.url }}">{{ project.url }}</a>
                    {% elif project.type == 'newsletter' %}
                        <strong>Newsletter:</strong> {{ project.title }} - <a href="{{ project.url }}">{{ project.url }}</a>
                    {% endif %}
                    {% if user.role == 'editor' and project.publisher == user.publisher %}
                        <!-- Editor options -->
                        <a href="{% url 'newsapp:edit_project' project.id %}">Edit</a>
                        <a href="{% url 'newsapp:approve_project' project.id %}">Approve</a>
                    {% endif %}
                </li>
            {% empty %}
                <li>You have not created any articles or newsletters.</li>
            {% endfor %}
        {% endwith %}
    </ul>

    {% if user.role != 'editor' %}
        <form method="post" action="{% url 'newsapp:create_project' %}">
            {% csrf_token %}
            <button type="submit">Create New Project</button>
        </form>
    {% endif %}
{% endblock %}