news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("users/", include("users.urls")),
    path("", include("newsapp.urls")),
    path("publishers/", include("publishers.urls")),
    

    # URL pattern for displaying password_reset view
    path('forgot-password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'
    ), name='password_reset'),

    path('forgot-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ),  name='password_reset_complete'),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_project/newsapp/urls.py
from django.urls import path
from .views import (
    create_article,
    dashboard,
    article_list,
    editor_dashboard,
    journalist_dashboard,
    approve_article,
    article_detail,
    article_update,
    article_delete,
    reader_dashboard,
    confirm_subscription,
    subscribe,
    unsub_to_journalist,
    unsub_to_publisher,
    newsletter_detail,
    newsletter_create,
    newsletter_update,
    newsletter_delete,
    subscribed_articles,
)

app_name = 'newsapp'

urlpatterns = [
    path('create/', create_article, name='create_article'),

    path('', dashboard, name='dashboard'),

    path('editor_dashboard/', editor_dashboard, name='editor_dashboard'),

    path('journalist/dashboard', journalist_dashboard, name="journalist_dashboard"),

    path('reader/dashboard/', reader_dashboard, name="reader_dashboard"),

    path('articles/article_list', article_list, name='article_list'),

    path('article/detail/<int:pk>/', article_detail, name='article_detail'),

    path('articles/update/<int:pk>/', article_update, name="article_update"),

    path('articles/delete/<int:pk>', article_delete, name="article_delete"),

    path("subscribe/confirm/<int:pk>/", confirm_subscription, name="confirm_subscription"),

    path("subscribe/<int:pk>/", subscribe, name="subscribe"),

    # path("subscribe/", subscribe, name="subscribe"),

    path('unsub/publisher/<int:pk>/', unsub_to_publisher, name="unsub_to_publisher"),

    path('unsub/journalist/<int:pk>/', unsub_to_journalist, name='unsub_to_journalist'),

    path('newsletter/detail', newsletter_detail, name='newsletter_detail'),

    path('newsletter/create', newsletter_create, name='newsletter_create'),

    path('newsletter/update', newsletter_update, name='newsletter_update'),

    path('newsletter/delete', newsletter_delete, name='newsletter_delete'),

    path('articles/approve/<int:pk>/', approve_article, name="approve_article"),

    path('api/subscribed-articles/<int:pk>/', subscribed_articles, name='subscribed-articles'),
]

news_project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    signup,
    login,
    logout_user,
    profile,
    reader_homepage,
    journalist_homepage,
    editor_homepage,
    sub_to_publisher,
    sub_to_journalist,
    unsub_to_journalist,
    unsub_to_publisher
)

app_name = 'users'

urlpatterns = [
    # URL pattern for displaying signup view
    path("", signup, name="signup"),

    # URL pattern for displaying login_view
    path("login", login, name="login"),

    # URL pattern for loggin out user
    path("logout", logout_user, name="logout_user"),


    # URL pattern for displaying profile
    path("profile/", profile, name="profile"),

    # URL pattern for displaying password_reset view
    path('forgot-password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'
    ), name='password_reset'),

    path('forgot-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ),  name='password_reset_complete'),

    path('reader-homepage/', reader_homepage, name='reader_homepage'),
    path('journalist-homepage/', journalist_homepage, name='journalist_homepage'),
    path('editor-homepage/', editor_homepage, name='editor_homepage'),

    # subscription paths
    path('subscribe/journalist/<int:pk>/', sub_to_journalist, name='sub_to_journalist'),
    path('subscribe/publisher/<int:pk>/', sub_to_publisher, name='sub_to_publisher'),

    path('unsubscribe/journalist/<int:pk>/', unsub_to_journalist, name='unsub_to_journalist'),
    path('unsubscribe/publisher/<int:pk>/', unsub_to_publisher, name='unsub_to_publisher'),
]

news_project/newsapp/views.py
import tweepy

from django.shortcuts import render, get_object_or_404, redirect
from .forms import ArticleForm, NewsletterForm
from users.models import CustomUser
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Article, Newsletter
from publishers.models import Publisher
from publishers.views import join_requests
from django.http import HttpResponseForbidden
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import ArticleSerializer


def announce_article_on_x(article_id):
    '''
    View to announce an article on X (formerly Twitter).

    :param article_id: ID of the article to be announced.
    :return: None. Posts a text-only announcement to X if the article exists.
    '''
    # Validating the article object.
    try:
        article = Article.objects.select_related().get(id=article_id)
    except Article.DoesNotExist:
        return
    client = tweepy.Client(
        consumer_key=settings.TWITTER_API_KEY,
        consumer_secret=settings.TWITTER_API_SECRET,
        access_token=settings.TWITTER_ACCESS_TOKEN,
        access_token_secret=settings.TWITTER_ACCESS_TOKEN_SECRET,
    )
    # Image settings.
    # auth = tweepy.OAuth1UserHandler(consumer_key=settings.TWITTER_API_KEY, consumer_secret=settings.TWITTER_API_SECRET, access_token=settings.TWITTER_ACCESS_TOKEN, access_token_secret=settings.TWITTER_ACCESS_TOKEN_SECRET)
    # v1_api = tweepy.API(auth)
    # media = v1_api.media_upload(store.cover_page.path)

    # X post (tweet).
    client.create_tweet(text=f"New Article Added: {article.title}")


@login_required
def create_article(request):
    '''
    View to create a new article.
    :param request: HTTP request object.
    :return: Rendered template for creating a new article.
    '''
    if request.method == "POST":
        form = ArticleForm(request.POST, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)

            # Always set the author
            article.author = request.user

            # Attach publication if the journalist belongs to one
            publishers = request.user.joined_publishers.all()
            if publishers.exists():
                article.publisher = publishers.first()
            else:
                # Independent journalist
                article.publisher = None
                # article.independent_author.set(request.user)

            # Force safe defaults
            # article.status = "pending"        # Never published automatically
            # article.is_approved = False     # Never approved automatically

            article.save()
            article.independent_author.add(request.user)
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(user=request.user)

    return render(request, "articles/article_form.html", {"form": form})


@login_required
def article_list(request):
    '''
    This view will display a list of articles/newsletters

        :param request: HTTP object
        :return: Rendered template with a list of articles/newsletters
    '''
    articles = Article.objects.filter(is_approved=True)
    newsletters = Newsletter.objects.filter(is_approved=True)

    context = {
        "articles": articles,
        "newsletters": newsletters,
        "page_title": "All Articles"
    }

    return render(request, "articles/article_list.html", context)


@login_required
def article_detail(request, pk):
    '''
    View to display details of a specific article.
    :param request: HTTP request object.
    :param pk: Primary key of the article.
    :return: Rendered template with details of the specified article.
    '''
    article = get_object_or_404(Article, pk=pk)
    context = {
        "article": article
    }
    return render(request, "articles/article_detail.html", context)


@login_required
def article_update(request, pk):
    '''
    View to update an existing article.
    :param request: HTTP request object.
    :param pk: Primary key of the article to be updated.
    :return: Rendered template for updating the specified article.
    '''

    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)
            article.save()
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(instance=article, user=request.user)
    return render(request, "articles/article_form.html", {"form": form})


@login_required
def article_delete(request, pk):
    '''
    View to delete an existing article.
    :param request: HTTP request object.
    :param pk: Primary key of the article to be deleted.
    :return: Redirect to the article list after deletion.
    '''

    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect("newsapp:article_list")


@login_required
def newsletter_create(request):
    '''
    View to create a new newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to the article list after creation.
    '''
    if request.method == "POST":
        form = NewsletterForm(request.POST, user=request.user)
        if form.is_valid():
            newsletter = form.save(commit=False)

            # Always set the author
            newsletter.author = request.user

            # Attach publication if the journalist belongs to one
            publishers = request.user.joined_publishers.all()
            if publishers.exists():
                newsletter.publisher = publishers.first()
            else:
                # Independent journalist
                newsletter.publisher = None
                # article.independent_author.set(request.user)

            newsletter.save()
            newsletter.independent_author.add(request.user)
            return redirect("newsapp:article_list")
    else:
        form = ArticleForm(user=request.user)

    return render(request, "articles/article_form.html", {"form": form})


def newsletter_list(request):
    '''
    This view will display a list of articles/newsletters

        :param request: HTTP object
        :return: Rendered template with a list of articles/newsletters
    '''
    if request.user.role == 'reader':
        newsletters = Newsletter.objects.filter(is_approved=True)
    else:
        newsletters = Newsletter.objects.all()

        context = {
            "newsletters": newsletters,
            "page_title": "All newsletters"
        }

        return render(request, "newsletters/newsletter_list.html", context)


@login_required
@user_passes_test(lambda u: u.role == 'editor')
def newsletter_update(request, pk):
    '''
    View to update an existing newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter to be updated.
    :return: Rendered template for updating the specified newsletter.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        form = NewsletterForm(request.POST, instance=newsletter)
        if form.is_valid():
            newsletter = form.save(commit=False)
            newsletter.journalist = request.user
            newsletter.publisher = request.publisher
            form.save()
        return redirect("newsletters: newsletter_list")
    else:
        form = NewsletterForm()
    return render(request, "newsletters/newsletter_form.html", {"form": form})


@login_required
@user_passes_test(lambda u: u.role == 'editor')
def newsletter_delete(request, pk):
    '''
    View to delete an existing newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter to be deleted.
    :return: Redirect to the newslleter list after deletion.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    newsletter.delete()
    return redirect("newsletters: newsletter_list")


def newsletter_detail(request, pk):
    '''
    View to display details of a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Rendered template with details of the specified newsletter.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    context = {
        "newsletter": newsletter
    }
    return render(request, "newsletters/newsletter_detail.html", context)


def approve_newsletter(request, pk):
    '''
    View to display approve a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to newsletter_list.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.user.role == 'editor':
        newsletter.is_approved = True
        newsletter.save()
    return redirect('newsletters:newsletter_list')


def reject_newsletter(request, pk):
    '''
    View to display reject a specific newsletter.
    :param request: HTTP request object.
    :param pk: Primary key of the newsletter.
    :return: Redirect to newsletter_list.
    '''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.user.role == 'editor':
        newsletter.is_approved = False
        newsletter.save()
    return redirect('newsletters:newsletter_list')


def approve_article(request, pk):
    '''
    View to display approve a specific article.
    :param request: HTTP request object.
    :param pk: Primary key of the article.
    :return: Redirect to article_list.
    '''
    article = get_object_or_404(Article, pk=pk)
    if request.user.role == 'editor':
        article.is_approved = True
        # announce_article_on_x(article_id=article.id)
        article.save()
    return redirect('newsapp:article_list')

news_project/newsapp/templates/articles/article_detail.html
{% extends "base.html" %}

{% block content %}

<style>
.article-container {
    max-width: 800px;
    margin: 0 auto;
}

.article-meta {
    color: #555;
    margin-bottom: 8px;
}

.article-actions {
    margin-top: 20px;
}

.article-actions h3 {
    margin-bottom: 10px;
}

.article-actions a,
.article-actions button {
    margin-right: 8px;
    margin-bottom: 8px;
}

button {
    padding: 6px 12px;
    cursor: pointer;
}
</style>

<div class="article-container">

    <h1>{{ article.title }}</h1>

    <p class="article-meta">
        <strong>Author:</strong> {{ article.journalist }}
    </p>

    <p class="article-meta">
        <strong>Status:</strong>
        {% if article.approved %}
            Published
        {% else %}
            Draft / Pending
        {% endif %}
    </p>

    <hr>

    <p>{{ article.content }}</p>

    <hr>

    {# ===== JOURNALIST ACTIONS ===== #}
    {% if user.role == "journalist" and article.author == user %}
        <div class="article-actions">
            <h3>Journalist Actions</h3>

            <a href="{% url 'newsapp:article_update' article.pk %}">
                <button>Edit Article</button>
            </a>

            <a href="{% url 'newsapp:article_delete' article.pk %}">
                <button>Delete Article</button>
            </a>
        </div>
    {% endif %}

    {# ===== EDITOR ACTIONS ===== #}
    {% if user.role == "editor" and article.publisher and user.publisher == article.publisher %}
        <div class="article-actions">
            <h3>Editor Actions</h3>

            <a href="{% url 'newsapp:article_update' article.pk %}">
                <button>Edit Article</button>
            </a>

            <a href="{% url 'newsapp:article_delete' article.pk %}">
                <button>Delete Article</button>
            </a>

            {% if not article.approved %}
                <form method="post" action="{% url 'newsapp:approve_article' article.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Publish Article</button>
                </form>
            {% endif %}
        </div>
    {% endif %}

    {# ===== READERS: READ-ONLY (NO ACTIONS) ===== #}
    {% if user.role == "reader" %}
        <div class="article-actions">
            <form method="post" action="{% url 'newsapp:subscribe' article.pk %}">
                {% csrf_token %}
                <button type="submit">Subscribe</button>
            </form>
        </div>
    {% endif %}
    <a href="{% url 'newsapp:article_list' %}">
        <button type="button">Back to Articles</button>
    </a>

{% endblock %}

news_project/newsapp/templates/articles/article_form.html
{% extends 'base.html' %}

{% block content %}
    <html>
    <head>
        <meta charset="UTF-8" />
        <title>article form</title>
    </head>
    <body>
        <h1>article form</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
    </body>
    </html>
{% endblock %}

news_project/newsapp/templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper">
    <h1 class="page-title">Latest Publications</h1>

    <style>
        .content-wrapper {
    max-width: 900px;
    margin: 2rem auto;
    padding: 0 1rem;
}

.page-title {
    font-size: 2rem;
    margin-bottom: 1.5rem;
    border-bottom: 2px solid #eee;
    padding-bottom: .5rem;
}

.article-list {
    list-style: none;
    padding: 0;
    display: grid;
    gap: 1.5rem;
}

.card {
    background: #fff;
    padding: 1.5rem;
    border-radius: 8px;
    border: 1px solid #e5e5e5;
    transition: transform .15s ease, box-shadow .15s ease;
}

.card:hover {
    transform: translateY(-3px);
    box-shadow: 0 6px 18px rgba(0,0,0,0.08);
}

.newsletter {
    border-left: 5px solid #4f46e5;
}

.card-title {
    margin: 0 0 .5rem;
    font-size: 1.4rem;
}

.card-excerpt {
    color: #555;
    margin-bottom: .75rem;
}

.card-meta {
    font-size: .85rem;
    color: #777;
    margin-bottom: 1rem;
}

.card-link {
    text-decoration: none;
    font-weight: 600;
    color: #2563eb;
}

.card-link:hover {
    text-decoration: underline;
}

.empty {
    color: #888;
    font-style: italic;
}

    </style>
    
    <ul class="article-list">
        {% for article in articles %}
        <p> {{article.id}} </p>
            <li class="card">
                <h2 class="card-title">{{ article.title }}</h2>

                <p class="card-excerpt">
                    {{ article.content|truncatewords:30 }}
                </p>

                <p class="card-meta">
                    By <strong>{{ article.author.username }}</strong>
                    · {{ article.published_date }}
                </p>

                <a class="card-link"
                   href="{% url 'newsapp:article_detail' article.pk %}">
                    Read more →
                </a>
            </li>
        {% empty %}
            <li class="empty">No articles available.</li>
        {% endfor %}

        {% for newsletter in newsletters %}
            <li class="card newsletter">
                <h2 class="card-title">{{ newsletter.title }}</h2>

                <p class="card-excerpt">
                    {{ newsletter.content|truncatewords:30 }}
                </p>

                <p class="card-meta">
                    By <strong>{{ newsletter.author.username }}</strong>
                    · {{ newsletter.published_date }}
                </p>

                <a class="card-link"
                   href="{% url 'newsapp:newsletter_detail' newsletter.pk %}">
                    Read more →
                </a>
            </li>
        {% empty %}
            <li class="empty">No newsletters available.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

news_project/newsapp/templates/articles/newsletter_detail.html
{% extends "base.html" %}

{% block content %}

<style>
.article-container {
    max-width: 800px;
    margin: 0 auto;
}

.article-meta {
    color: #555;
    margin-bottom: 8px;
}

.article-actions {
    margin-top: 20px;
}

.article-actions h3 {
    margin-bottom: 10px;
}

.article-actions a,
.article-actions button {
    margin-right: 8px;
    margin-bottom: 8px;
}

button {
    padding: 6px 12px;
    cursor: pointer;
}
</style>

<div class="article-container">

    <h1>{{ newsletter.title }}</h1>

    <p class="article-meta">
        <strong>Author:</strong> {{ newsletter.journalist }}
    </p>

    <p class="article-meta">
        <strong>Status:</strong>
        {% if newsletter.approved %}
            Published
        {% else %}
            Draft / Pending
        {% endif %}
    </p>

    <hr>

    <p>{{ article.content }}</p>

    <hr>

    {# ===== JOURNALIST ACTIONS ===== #}
    {% if user.role == "journalist" and newsletter.author == user %}
        <div class="article-actions">
            <h3>Journalist Actions</h3>

            <a href="{% url 'newsapp:newsletter_update' newsletter.pk %}">
                <button>Edit Newsletter</button>
            </a>

            <a href="{% url 'newsapp:newsletter_delete' newsletter.pk %}">
                <button>Delete Newsletter</button>
            </a>
        </div>
    {% endif %}

    {# ===== EDITOR ACTIONS ===== #}
    {% if user.role == "editor" and newsletter.publisher and user.publisher == newsletter.publisher %}
        <div class="article-actions">
            <h3>Editor Actions</h3>

            <a href="{% url 'newsapp:newsletter_update' newsletter.pk %}">
                <button>Edit Article</button>
            </a>

            <a href="{% url 'newsapp:newsletter_delete' newsletter.pk %}">
                <button>Delete Article</button>
            </a>

            {% if not newsletter.approved %}
                <form method="post" action="{% url 'newsapp:approve_newsletter' newsletter.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Publish Newsletter</button>
                </form>
            {% endif %}
        </div>
    {% endif %}

    {# ===== READERS: READ-ONLY (NO ACTIONS) ===== #}

    <hr>

<form method="post" action="{% url 'newsapp:subscribe' newsletter.pk %}">
    {% csrf_token %}
    <button type="submit">Subscribe</button>
</form>

<a href="{% url 'newsapp:article_list' %}">
    <button type="button">Back to Articles</button>
</a>

</div>

{% endblock %}